### ISSUE TITLE
Client: File upload UI and functionality

### ISSUE THREAD

**Issue by bewakes** [the-dive/dive-client#5]
- [x] Create card with Import button

![Image](https://user-images.githubusercontent.com/45554490/206139006-c21edf7d-37c5-4f54-9fdd-85460fff4b78.png)

- [x] Create Modal with file type 

![Image](https://user-images.githubusercontent.com/45554490/206139368-9cc8a6ac-eda3-4702-bc8d-50195c410f83.png)

- [x] Integrate file upload API, show errors and progress

**Comment by shreeyash07** [comment]
Screenshot after completion:

- Card with import button

![Image](https://user-images.githubusercontent.com/45554490/206357093-5c8ae5f0-07bc-4c76-9968-ccce452b6281.png)

- Modal

![Image](https://user-images.githubusercontent.com/45554490/206430928-b525a9a9-c073-4e0a-a7bf-fda2cfa5b44c.png)
